/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zipkinCore_CONSTANTS_H
#define zipkinCore_CONSTANTS_H

#include "zipkinCore_types.h"



class zipkinCoreConstants {
 public:
  zipkinCoreConstants();

  std::string CLIENT_SEND;
  std::string CLIENT_RECV;
  std::string SERVER_SEND;
  std::string SERVER_RECV;
};

extern const zipkinCoreConstants g_zipkinCore_constants;



#endif
